Repository apcountryman/picolibrary, pull requests merged in 2021-03, with the labels that each got.

#350 Fix Microchip MCP23008 internally pulled-up input pin unit test documentation
  test/unit/picolibrary/microchip/mcp23008/internally_pulled_up_input_pin/main.cc
Labels: priority-normal, status-awaiting_approval, type-bug

#346 Add fixed intensity indicator concept
  include/picolibrary/indicator.h
  include/picolibrary/testing/unit/indicator.h
Labels: priority-normal, status-awaiting_approval, type-feature

#351 Remove deleted special member function named arguments
  include/picolibrary/microchip/mcp23008.h
Labels: priority-normal, status-awaiting_approval, type-refactoring

#352 Document special member functions expected by concepts
  include/picolibrary/adc.h
  include/picolibrary/asynchronous_serial.h
  include/picolibrary/crc.h
  include/picolibrary/gpio.h
  include/picolibrary/i2c.h
  include/picolibrary/indicator.h
  include/picolibrary/spi.h
Labels: priority-normal, status-awaiting_approval, type-enhancement

#358 Add Microchip MCP23008 driver register abstractions
  include/picolibrary/microchip/mcp23008.h
  include/picolibrary/testing/unit/microchip/mcp23008.h
  test/unit/picolibrary/microchip/mcp23008/driver/main.cc
Labels: priority-normal, status-awaiting_approval, type-enhancement

#362 Refactor Microchip MCP23008 internally pulled-up input pin to use driver register abstractions
  include/picolibrary/microchip/mcp23008.h
  test/unit/picolibrary/microchip/mcp23008/internally_pulled_up_input_pin/main.cc
Labels: priority-normal, status-awaiting_approval, type-refactoring

#363 Refactor Microchip MCP23008 open-drain output pin to use driver register abstractions
  include/picolibrary/microchip/mcp23008.h
  test/unit/picolibrary/microchip/mcp23008/open_drain_io_pin/main.cc
Labels: priority-normal, status-awaiting_approval, type-refactoring

#365 Fix Microchip MCP23008 open-drain I/O pin unit test names/documantion
  test/unit/picolibrary/microchip/mcp23008/open_drain_io_pin/main.cc
Labels: priority-normal, status-awaiting_approval, type-bug

#366 Refactor Microchip MCP23008 push-pull I/O pin to use driver register abstractions
  include/picolibrary/microchip/mcp23008.h
  test/unit/picolibrary/microchip/mcp23008/push_pull_io_pin/main.cc
Labels: priority-normal, status-awaiting_approval, type-refactoring

#369 Update Microchip MCP23008 pin abstraction ignored error warnings
  include/picolibrary/microchip/mcp23008.h
Labels: priority-normal, status-awaiting_approval, type-refactoring

#370 Improve Microchip MCP23008 configuration type/argument names
  include/picolibrary/microchip/mcp23008.h
  include/picolibrary/testing/unit/microchip/mcp23008.h
  test/unit/picolibrary/microchip/mcp23008/driver/main.cc
Labels: priority-normal, status-awaiting_approval, type-refactoring

#374 Add caller provided output stream support to GPIO output pin toggle interactive test helper
  include/picolibrary/testing/interactive/gpio.h
Labels: priority-normal, status-awaiting_approval, type-refactoring

#375 Add caller provided output stream support to GPIO input pin state interactive test helper
  include/picolibrary/testing/interactive/gpio.h
Labels: priority-normal, status-awaiting_approval, type-refactoring

#376 Add caller provided output stream support to blocking, single sample ADC sample interactive test helper
  include/picolibrary/testing/interactive/adc.h
Labels: priority-normal, status-awaiting_approval, type-refactoring

#377 Refactor Microchip MCP3008 sample interactive test helper to report more errors to the user
  include/picolibrary/testing/interactive/microchip/mcp3008.h
Labels: priority-normal, status-awaiting_approval, type-refactoring

#353 Add GPIO output pin based fixed intensity indicator
  include/picolibrary/indicator.h
  test/unit/picolibrary/CMakeLists.txt
  test/unit/picolibrary/indicator/CMakeLists.txt
  test/unit/picolibrary/indicator/gpio_output_pin_fixed_intensity_indicator/CMakeLists.txt
  test/unit/picolibrary/indicator/gpio_output_pin_fixed_intensity_indicator/main.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#378 Add Microchip MCP23008 internally pulled-up input pin state interactive test helper
  include/picolibrary/testing/interactive/microchip/mcp23008.h
Labels: priority-normal, status-awaiting_approval, type-feature

#379 Add Microchip MCP23008 output pin toggle interactive test helper
  include/picolibrary/testing/interactive/microchip/mcp23008.h
Labels: priority-normal, status-awaiting_approval, type-feature

#381 Fix Microchip MCP23008 internally pulled-up input pin state interactive test helper documentation
  include/picolibrary/testing/interactive/microchip/mcp23008.h
Labels: priority-normal, status-awaiting_approval, type-bug

#382 Add project issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/enhancement-design.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/feature-design.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: priority-normal, status-awaiting_approval, type-feature

#383 Add project pull request templates
  .github/PULL_REQUEST_TEMPLATE/bug.md
  .github/PULL_REQUEST_TEMPLATE/enhancement.md
  .github/PULL_REQUEST_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE/refactoring.md
Labels: priority-normal, status-awaiting_approval, type-feature

#386 Remove pull request template headers
  .github/PULL_REQUEST_TEMPLATE/bug.md
  .github/PULL_REQUEST_TEMPLATE/enhancement.md
  .github/PULL_REQUEST_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE/refactoring.md
Labels: priority-normal, status-awaiting_approval, type-refactoring

#388 Add default pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: priority-normal, status-awaiting_approval, type-enhancement

#390 Remove custom pull request templates
  .github/PULL_REQUEST_TEMPLATE/bug.md
  .github/PULL_REQUEST_TEMPLATE/enhancement.md
  .github/PULL_REQUEST_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE/refactoring.md
Labels: priority-normal, status-awaiting_approval, type-refactoring

#391 Modularize project build configuration files
  ci/analyze
  ci/build
  configuration/analysis/CMakeLists.txt
  configuration/release/CMakeLists.txt
  configuration/testing-interactive/CMakeLists.txt
  configuration/testing-unit/CMakeLists.txt
  git/hooks/pre-commit
Labels: priority-normal, status-awaiting_approval, type-refactoring

#394 Refactor CI workflow to only trigger on push or pull request for the main branch
  .github/workflows/ci.yml
Labels: priority-normal, status-awaiting_approval, type-refactoring

#396 Update submodule URLs
  .gitmodules
Labels: priority-normal, status-awaiting_approval, type-refactoring

#392 Add project contributing guidelines
  CONTRIBUTING.md
  README.md
Labels: priority-normal, status-awaiting_approval, type-feature

#398 Update issue and pull request templates to reflect project contributing guidelines
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/enhancement-design.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/feature-design.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: priority-normal, status-awaiting_approval, type-refactoring

#399 Add project code of conduct
  CODE_OF_CONDUCT.md
  README.md
Labels: priority-normal, status-awaiting_approval, type-feature

#403 Update CI scripts to use CMake to create build directories
  ci/analyze
  ci/build
Labels: priority-normal, status-awaiting_approval, type-refactoring

#404 Fix contributing guidelines wording/punctuation
  CONTRIBUTING.md
  README.md
Labels: priority-normal, status-awaiting_approval, type-bug

#409 Link CI status badge to CI workflow runs
  README.md
Labels: priority-normal, status-awaiting_approval, type-enhancement

#410 Reword question issue template and contributing guidelines
  .github/ISSUE_TEMPLATE/question.md
  CONTRIBUTING.md
Labels: priority-normal, status-awaiting_approval, type-refactoring
