Repository apcountryman/picolibrary, pull requests merged in 2021-02, with the labels that each got.

#203 Add nonresponsive device generic error
  include/picolibrary/error.h
  test/unit/picolibrary/generic_error_category/main.cc
Labels: priority-normal, status-awaiting_approval, type-enhancement

#207 Add ADC interactive testing facilities namespace
  include/picolibrary/testing/interactive/adc.h
  source/CMakeLists.txt
  source/picolibrary/testing/interactive/adc.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#208 Add blocking, single sample ADC sample interactive test helper
  include/picolibrary/testing/interactive/adc.h
Labels: priority-normal, status-awaiting_approval, type-feature

#209 Add Microchip interactive testing facilities namespace
  include/picolibrary/testing/interactive/microchip.h
  source/CMakeLists.txt
  source/picolibrary/testing/interactive/microchip.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#210 Add Microchip MCP3008 interactive testing facilities namespace
  include/picolibrary/testing/interactive/microchip/mcp3008.h
  source/CMakeLists.txt
  source/picolibrary/testing/interactive/microchip/mcp3008.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#211 Add Microchip MCP3008 sample interactive test helper
  include/picolibrary/testing/interactive/microchip/mcp3008.h
Labels: priority-normal, status-awaiting_approval, type-feature

#213 Improve blocking, single sample ADC sample interactive test helper documentation
  include/picolibrary/testing/interactive/adc.h
Labels: priority-normal, status-awaiting_approval, type-enhancement

#218 Remove Doxygen generated documentation
  CMakeLists.txt
  documentation/Doxyfile.in
  documentation/mainpage.md
  include/picolibrary/adc.h
  include/picolibrary/asynchronous_serial.h
  include/picolibrary/asynchronous_serial/stream.h
  include/picolibrary/error.h
  include/picolibrary/format.h
  include/picolibrary/gpio.h
  include/picolibrary/microchip/mcp3008.h
  include/picolibrary/result.h
  include/picolibrary/spi.h
  include/picolibrary/stream.h
  include/picolibrary/testing/unit/adc.h
  include/picolibrary/testing/unit/asynchronous_serial.h
  include/picolibrary/testing/unit/error.h
  include/picolibrary/testing/unit/gpio.h
  include/picolibrary/testing/unit/microchip/mcp3008.h
  include/picolibrary/testing/unit/spi.h
  include/picolibrary/testing/unit/stream.h
  test/unit/picolibrary/output_stream/main.cc
Labels: priority-normal, status-awaiting_approval, type-refactoring

#221 Remove references to issue #34
  include/picolibrary/result.h
Labels: priority-normal, status-awaiting_approval, type-refactoring

#222 Increase compilation warnings
  CMakeLists.txt
  configuration/CMakeLists.txt.analysis
  configuration/CMakeLists.txt.release
  configuration/CMakeLists.txt.testing-interactive
  configuration/CMakeLists.txt.testing-unit
Labels: priority-normal, status-awaiting_approval, type-enhancement

#224 Update clang-format configuration
  .clang-format
  include/picolibrary/algorithm.h
  include/picolibrary/asynchronous_serial.h
  include/picolibrary/crc.h
  include/picolibrary/gpio.h
  include/picolibrary/iterator.h
  include/picolibrary/microchip/mcp3008.h
  include/picolibrary/result.h
  include/picolibrary/spi.h
  include/picolibrary/stream.h
  include/picolibrary/testing/interactive/adc.h
  include/picolibrary/testing/interactive/asynchronous_serial.h
  include/picolibrary/testing/interactive/asynchronous_serial/stream.h
  include/picolibrary/testing/interactive/gpio.h
  include/picolibrary/testing/interactive/microchip/mcp3008.h
  include/picolibrary/testing/unit/adc.h
  include/picolibrary/testing/unit/spi.h
  include/picolibrary/testing/unit/stream.h
  test/unit/picolibrary/format/binary/main.cc
  test/unit/picolibrary/format/hexadecimal/main.cc
  test/unit/picolibrary/spi/device/main.cc
Labels: priority-normal, status-awaiting_approval, type-enhancement

#227 Add CI format job
  .github/workflows/ci.yml
  ci/format
Labels: priority-normal, status-awaiting_approval, type-enhancement

#228 Update clang-tidy configuration
  .clang-tidy
Labels: priority-normal, status-awaiting_approval, type-enhancement

#236 Add Void formatted output
  include/picolibrary/stream.h
  test/unit/picolibrary/output_stream/main.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#239 Add SPI interactive testing facilities namespace
  include/picolibrary/testing/interactive/spi.h
  source/CMakeLists.txt
  source/picolibrary/testing/interactive/spi.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#240 Add SPI controller echo interactive test helper
  include/picolibrary/testing/interactive/spi.h
Labels: priority-normal, status-awaiting_approval, type-feature

#242 Fix SPI controller configuration documentation
  include/picolibrary/microchip/mcp3008.h
  include/picolibrary/spi.h
  include/picolibrary/testing/interactive/microchip/mcp3008.h
  include/picolibrary/testing/interactive/spi.h
  include/picolibrary/testing/unit/spi.h
Labels: priority-normal, status-awaiting_approval, type-bug

#250 Add I2C facilities namespace
  include/picolibrary/i2c.h
  source/CMakeLists.txt
  source/picolibrary/i2c.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#251 Add I2C unit testing facilities namespace
  include/picolibrary/testing/unit/i2c.h
  source/CMakeLists.txt
  source/picolibrary/testing/unit/i2c.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#252 Add I2C interactive testing facilities namespace
  include/picolibrary/testing/interactive/i2c.h
  source/CMakeLists.txt
  source/picolibrary/testing/interactive/i2c.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#253 Add I2C device address
  include/picolibrary/i2c.h
  include/picolibrary/testing/unit/i2c.h
  source/picolibrary/i2c.cc
  test/unit/picolibrary/CMakeLists.txt
  test/unit/picolibrary/i2c/CMakeLists.txt
  test/unit/picolibrary/i2c/address/CMakeLists.txt
  test/unit/picolibrary/i2c/address/main.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#254 Add I2C operation
  include/picolibrary/i2c.h
Labels: priority-normal, status-awaiting_approval, type-feature

#255 Add I2C response
  include/picolibrary/i2c.h
Labels: priority-normal, status-awaiting_approval, type-feature

#264 Add arbitration lost generic error
  include/picolibrary/error.h
  test/unit/picolibrary/generic_error_category/main.cc
Labels: priority-normal, status-awaiting_approval, type-enhancement

#265 Add I2C basic controller concept
  include/picolibrary/i2c.h
  include/picolibrary/testing/unit/i2c.h
Labels: priority-normal, status-awaiting_approval, type-feature

#266 Add I2C controller concept
  include/picolibrary/i2c.h
  include/picolibrary/testing/unit/i2c.h
Labels: priority-normal, status-awaiting_approval, type-feature

#269 Add pseudo-random I2C operation generation
  include/picolibrary/testing/unit/i2c.h
Labels: priority-normal, status-awaiting_approval, type-enhancement

#270 Add pseudo-random I2C response generation
  include/picolibrary/testing/unit/i2c.h
Labels: priority-normal, status-awaiting_approval, type-enhancement

#274 Add I2C unit test program skeleton
  test/unit/picolibrary/i2c/CMakeLists.txt
  test/unit/picolibrary/i2c/main.cc
Labels: priority-normal, status-awaiting_approval, type-enhancement

#275 Add I2C device ping
  include/picolibrary/i2c.h
  test/unit/picolibrary/i2c/main.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#276 Add I2C bus scan
  include/picolibrary/i2c.h
  test/unit/picolibrary/i2c/main.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#277 Add I2C bus scan interactive test helper
  include/picolibrary/testing/interactive/i2c.h
Labels: priority-normal, status-awaiting_approval, type-feature

#279 Add character formatted output
  include/picolibrary/stream.h
  test/unit/picolibrary/output_stream/main.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#281 Use characters to hold I2C bus scan interactive test helper printed operations
  include/picolibrary/testing/interactive/i2c.h
Labels: priority-normal, status-awaiting_approval, type-refactoring

#288 Add logic error generic error
  include/picolibrary/error.h
  test/unit/picolibrary/generic_error_category/main.cc
Labels: priority-normal, status-awaiting_approval, type-enhancement

#289 Add bus error generic error
  include/picolibrary/error.h
  test/unit/picolibrary/generic_error_category/main.cc
Labels: priority-normal, status-awaiting_approval, type-enhancement

#293 Fix I2C bus scan interactive test helper devices found report
  include/picolibrary/testing/interactive/i2c.h
Labels: priority-normal, status-awaiting_approval, type-bug

#294 Fix I2C device ping bus lock up
  include/picolibrary/i2c.h
  test/unit/picolibrary/i2c/main.cc
Labels: priority-normal, status-awaiting_approval, type-bug

#297 Add I2C device
  include/picolibrary/i2c.h
Labels: priority-normal, status-awaiting_approval, type-feature

#290 Add indicator facilities namespace
  include/picolibrary/indicator.h
  source/picolibrary/indicator.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#299 Add mock I2C device
  include/picolibrary/testing/unit/i2c.h
Labels: priority-normal, status-awaiting_approval, type-enhancement

#301 Update authors list
  README.md
Labels: priority-normal, status-awaiting_approval, type-enhancement

#303 Change I2C device template parameter order
  include/picolibrary/i2c.h
  test/unit/picolibrary/i2c/device/CMakeLists.txt
  test/unit/picolibrary/i2c/device/uint8_t/CMakeLists.txt
  test/unit/picolibrary/i2c/device/uint8_t/main.cc
Labels: priority-normal, status-awaiting_approval, type-refactoring

#306 Add error reporting to GPIO output pin toggle interactive test helper
  include/picolibrary/testing/interactive/gpio.h
Labels: priority-normal, status-awaiting_approval, type-enhancement

#316 Add NOP
  include/picolibrary/utility.h
Labels: priority-normal, status-awaiting_approval, type-feature

#318 Add Microchip MCP23008 register definitions
  include/picolibrary/microchip/mcp23008.h
Labels: priority-normal, status-awaiting_approval, type-feature

#320 Add "Microchip MCP23008" prefix to Microchip MCP23008 register documentation
  include/picolibrary/microchip/mcp23008.h
Labels: priority-normal, status-awaiting_approval, type-enhancement

#321 Add GPIO input pin state interactive test helper
  include/picolibrary/testing/interactive/gpio.h
Labels: priority-normal, status-awaiting_approval, type-feature

#323 Add Microchip MCP23008 configuration enums
  include/picolibrary/microchip/mcp23008.h
  include/picolibrary/testing/unit/microchip/mcp23008.h
Labels: priority-normal, status-awaiting_approval, type-feature

#324 Add Microchip MCP23008 device address range
  include/picolibrary/microchip/mcp23008.h
  source/picolibrary/microchip/mcp23008.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#326 Fix mock 8-bit register address space I2C device read register constness
  include/picolibrary/testing/unit/i2c.h
Labels: priority-normal, status-awaiting_approval, type-bug

#329 Add Microchip MCP23008 interrupt context
  include/picolibrary/microchip/mcp23008.h
Labels: priority-normal, status-awaiting_approval, type-feature

#331 Remove Microchip MCP23008 register cache initialization access protection
  include/picolibrary/microchip/mcp23008.h
  test/unit/picolibrary/microchip/mcp23008/register_cache/main.cc
Labels: priority-normal, status-awaiting_approval, type-refactoring

#337 Fix indicator facilities source file is not built
  source/CMakeLists.txt
Labels: priority-normal, status-awaiting_approval, type-bug

#339 Fix Microchip MCP23008 mock driver write register function signatures
  include/picolibrary/testing/unit/microchip/mcp23008.h
Labels: priority-normal, status-awaiting_approval, type-bug

#341 Add pseudo-random GPIO initial pull-up state generation
  include/picolibrary/testing/unit/gpio.h
Labels: priority-normal, status-awaiting_approval, type-enhancement

#342 Add Microchip MCP23008 internally pulled-up input pin
  include/picolibrary/microchip/mcp23008.h
  test/unit/picolibrary/microchip/mcp23008/CMakeLists.txt
  test/unit/picolibrary/microchip/mcp23008/internally_pulled_up_input_pin/CMakeLists.txt
  test/unit/picolibrary/microchip/mcp23008/internally_pulled_up_input_pin/main.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#335 Add indicator unit testing facilities namespace
  include/picolibrary/testing/unit/indicator.h
  source/CMakeLists.txt
  source/picolibrary/testing/unit/indicator.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#344 Add initial indicator state
  include/picolibrary/indicator.h
  include/picolibrary/testing/unit/indicator.h
Labels: priority-normal, status-awaiting_approval, type-feature
